"""add access fields to student and teacher

Revision ID: b80efc5dfbd7
Revises: 
Create Date: 2025-05-09 13:29:08.587148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80efc5dfbd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('access_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thesis_quota', sa.Integer(), nullable=True))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('access_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thesis_quota', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('thesis_quota')
        batch_op.drop_column('access_level')
        batch_op.drop_column('organization')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('thesis_quota')
        batch_op.drop_column('access_level')
        batch_op.drop_column('organization')

    # ### end Alembic commands ###
