from .base import db
from .student import Student
from .teacher import Teacher
from .o_convener import OConvener
from .bank_config import BankConfig
from .thesis import Thesis
from .log import AccessLog
from .api_config import APIConfig
from .T_admin import TAdmin
from .course import Course
