"""initial migration

Revision ID: 72e03a847142
Revises: 
Create Date: 2025-05-17 23:44:10.401748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72e03a847142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('o_convener', schema=None) as batch_op:
        batch_op.alter_column('is_pay',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thesis_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('course_enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thesis_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('course_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('course_enabled')
        batch_op.drop_column('thesis_enabled')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('course_enabled')
        batch_op.drop_column('thesis_enabled')

    with op.batch_alter_table('o_convener', schema=None) as batch_op:
        batch_op.alter_column('is_pay',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
