"""Add uploader to Thesis

Revision ID: 815ffb1ffa87
Revises: 9f8585966de2
Create Date: 2025-05-10 13:49:59.860627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815ffb1ffa87'
down_revision = '9f8585966de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.drop_column('uploader')

    # ### end Alembic commands ###
