"""Add is_check to Thesis

Revision ID: 907bdd23a0b0
Revises: 815ffb1ffa87
Create Date: 2025-05-10 14:01:08.784014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907bdd23a0b0'
down_revision = '815ffb1ffa87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_check', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.drop_column('is_check')

    # ### end Alembic commands ###
