"""add thesis model

Revision ID: 9f8585966de2
Revises: b80efc5dfbd7
Create Date: 2025-05-09 14:45:10.210004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8585966de2'
down_revision = 'b80efc5dfbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_scope', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('access_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_free', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.drop_column('is_free')
        batch_op.drop_column('access_type')
        batch_op.drop_column('access_scope')

    # ### end Alembic commands ###
